---
- name: "Set default ruby version"
  command: /bin/bash -lc 'mise use --global ruby@{{ ruby_version }}'
  become_user: "{{ item }}"
  loop: "{{ mise_users }}"
  # Disable use of PTY as it sometimes hangs
  async: 600
  poll: 2
